version: '3'
services:
  # MySQL Service
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: bookapi
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # Laravel API Service
  api:
    build:
      context: ./api
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bookapi
      DB_USERNAME: app
      DB_PASSWORD: password
    volumes:
      - ./api:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db

  # Nuxt.js Client Service
  client:
    build:
      context: ./client
    environment:
      VITE_API_URL: http://api:8000
    volumes:
      - ./client:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - app-network

  # Nginx Service acting as a Reverse Proxy
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:


